#!/bin/bash
./ris2sql && \
dropdb bibliography;
createdb bibliography && \
psql -f notes.sql bibliography && \
psql -f keywords.sql bibliography  && \
psql -f authors.sql bibliography && \
psql -f core.sql bibliography && \
psql -f author_uris.sql bibliography
